package com.chaplin.roots.maven.fixture.pages;

import com.chaplin.roots.PageContext;
import com.chaplin.roots.annotation.Prerender;
import com.chaplin.roots.html.Node;

import static com.chaplin.roots.html.Html.main;

@Prerender
public final class Page implements com.chaplin.roots.Page {
    @Override
    public Node render(PageContext context) {
        return main("Generated by the Maven plugin");
    }
}
