package dev.roots.maven.fixture.pages;

import dev.roots.PageContext;
import dev.roots.annotation.Prerender;
import dev.roots.html.Node;

import static dev.roots.html.Html.main;

@Prerender
public final class Page implements dev.roots.Page {
    @Override
    public Node render(PageContext context) {
        return main("Generated by the Maven plugin");
    }
}
