CREATE TABLE kanban_tasks (
    id VARCHAR(36) PRIMARY KEY,
    number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    title VARCHAR(160) NOT NULL,
    description VARCHAR(8000) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('BACKLOG','READY','IN_PROGRESS','DONE')),
    priority VARCHAR(12) NOT NULL CHECK (priority IN ('LOW','MEDIUM','HIGH','URGENT')),
    assignee VARCHAR(80) NOT NULL,
    due_date DATE,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 1,
    updated_by VARCHAR(256) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX kanban_tasks_board ON kanban_tasks (archived, status, number);
CREATE TABLE kanban_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(36) NOT NULL REFERENCES kanban_tasks(id),
    actor VARCHAR(256) NOT NULL,
    action VARCHAR(120) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX kanban_activity_task ON kanban_activity (task_id, id);
